version: '3'
services:
  legacy-submission-processor:
    image: legacy-submission-processor:latest
    container_name: legacy-submission-processor
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - "../.nyc_output:/app/.nyc_output"
      - "../coverage:/app/coverage"
    network_mode: "host"
